### PR TITLE
feat: update to angular V17

### PR DESCRIPTION
**Pull request by sheikalthaf**
- Update to angular v17
- Migrated to standalone application
- Migrated to angular project structure
- Deleted unused files

### CODE REVIEW

**Comment by sheikalthaf** [comment]
@mariohmol can you review this PR

**Comment by mariohmol** [comment]
this looks great, thanks @sheikalthaf 

will take a look on that tonight

**Comment by gasparbarancelli** [comment]
Need some help with proofreading? I believe that many users are waiting for the release of their component for Angular 17

**Comment by tcseh** [comment]
@mariohmol have you had a chance to take a look at this? We depend on this library and would love to update to the latest Angular :)

**Comment by sheikalthaf** [comment]
@gasparbarancelli @tcseh @mariohmol I see lots of users are waiting for V17 support, I just published the V17 in npm https://www.npmjs.com/package/@ngu/jsoneditor . @mariohmol If you like i can maintain the library and publish the packages in future.

**Comment by Sathyaraj06** [comment]
Is this PR Approved? Can we implement for angular 17 application if possible?

**Comment by on3dd** [comment]
Please merge it already 🙏🏻

**Comment by samantha-swift** [comment]
Is there any progress on merging this PR? Desperately need V17 support for our prod application

**Comment by pierakim** [comment]
Please merge it. Thks. 👀

**Comment by dails08** [comment]
> @gasparbarancelli @tcseh @mariohmol I see lots of users are waiting for V17 support, I just published the V17 in npm https://www.npmjs.com/package/@ngu/jsoneditor . @mariohmol If you like i can maintain the library and publish the packages in future.

Yeah, seems dead. Thanks for the offer to pick it up. Probably oughta just fork it, post your fork here so people coming here know where to find the living version of the library, and we'll all slowly shift over.

**Comment by sheikalthaf** [comment]
@dails08  I have already published the package to npm and also going to maintain it for furthur also

https://www.npmjs.com/package/@ngu/jsoneditor

**Comment by dails08** [comment]
> @dails08 I have already published the package to npm and also going to maintain it for furthur also
> 
> https://www.npmjs.com/package/@ngu/jsoneditor

Oh wow, I totally missed that. Thank you!

**Comment by dails08** [comment]
> @dails08 I have already published the package to npm and also going to maintain it for furthur also
> 
> https://www.npmjs.com/package/@ngu/jsoneditor

I'm having some issues using your published version. I don't seem to be able to create an issue on the repository; is there a way you'd like feedback provided?

**Comment by sheikalthaf** [comment]
> > @dails08 I have already published the package to npm and also going to maintain it for furthur also
> > https://www.npmjs.com/package/@ngu/jsoneditor
> 
> I'm having some issues using your published version. I don't seem to be able to create an issue on the repository; is there a way you'd like feedback provided?

@dails08 now i have enabled the issues now. can you log now

**Comment by mariohmol** [comment]
merged it.. but not sure how to publish the final lib without ng-packagr..

any ideas?

**Comment by pierakim** [comment]
Thks a lot @mariohmol you're the real rocker. :) 

Note:

Update:
`import { NgJsonEditorModule } from 'ang-jsoneditor';`
to
import { JsonEditorComponent } from 'ang-jsoneditor';

**Pull request merged**
