### PR TITLE
Upgrade to angular 16

### PR DESCRIPTION
**Pull request by legrottagliegionata**

### CODE REVIEW

**Comment by whernebrink** [comment]
Please approve this one?

**Comment by legrottagliegionata** [comment]
This is a fork, you can use a real repo

**Comment by whernebrink** [comment]
> This is a fork, you can use a real repo

@legrottagliegionata Still, would be nice if @mariohmol would merge and publish a new release of this library? So that we that uses this library, and want to upgrade to Angular, could continue using this awesome lib (as previous).

**Comment by mariohmol** [comment]
published on ang-jsoneditor@3.1.1

thanks a lot

**Pull request merged**
