### PR TITLE
jsonChange Event added

### PR DESCRIPTION
**Pull request by osmanraifgunes**
I created jsonChange event to be able to get json content by events. 

change event is crashing if the editor is in view mode and has enum in json schema (Added example schma in demo).

### CODE REVIEW

**Comment by mariohmol** [comment]
thank you.. i'm going just make a retest here and will merge tomorrow!

thanks

**Comment by mariohmol** [comment]
Hi!
Why did u change from `(change)` to `(jsonChange)` ?

**Comment by osmanraifgunes** [comment]
It is a new event and I tested it in example component.

**Comment by mariohmol** [comment]
yeah.. i confused myself.. now the demo is using the new style.. its cool! 
thanks =)

**Pull request merged**
