### PR TITLE
Add some missing properties to options

### PR DESCRIPTION
**Pull request by intellix**
These properties are listed here: https://github.com/josdejong/jsoneditor/blob/master/docs/api.md

Also took the JSDoc for them

### CODE REVIEW

**Comment by mariohmol** [comment]
Hi.. thanks for that... 

I bumped the version to 1.6.1 . did a demo components with this new two options.. but didn't see changes when status bar working...

**Comment by intellix** [comment]
with `(options as any).statusBar = false` the bottom bar disappears for me. I'm using these versions:
```
"ang-jsoneditor": "1.6.0",
"jsoneditor": "5.19.2"
```

**Comment by mariohmol** [comment]
I see.. check if in the demos is working for you 

https://github.com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.ts#L83

**Comment by intellix** [comment]
Added here: https://stackblitz.com/edit/angular-json-editor?file=src%2Fapp%2Fapp.component.ts

**Comment by mariohmol** [comment]
Awesome!! thanks!

**Pull request merged**
